# Generated by Django 4.2.2 on 2023-07-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MensajesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='timestamp',
        ),
    ]
