# Generated by Django 4.2.2 on 2023-07-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MensajesApp', '0002_rename_fecha_mensaje_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mensajes_images/'),
        ),
    ]
